version: '3'
services:
  load_balancer1:
    build:
      context: ./nginx-lb1
    ports:
      - "8081:8080"
    depends_on:
      - registry
      - db
      - persistence
      - auth
      - image
      - recommender
      - webui
      - redis
      - rabbitmq

  load_balancer2:
    build:
      context: ./nginx-lb2
    ports:
      - "8082:8080"
    depends_on:
      - registry
      - db
      - persistence
      - auth
      - image
      - recommender
      - webui
      - redis
      - rabbitmq

  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"

  redis-init:
    build:
      context: ./redis-init
    depends_on:
      - redis

  rabbitmq:
    image: descartesresearch/teastore-kieker-rabbitmq
    expose:
      - "15672"
      - "5672"
      - "8080"
    ports:
      - "15672:15672" 
      - "5672:5672"    
      - "8088:8080"     
    depends_on:
      - db
      - registry

  registry:
    image: descartesresearch/teastore-registry
    expose:
      - "8080"
    ports:
      - "8083:8080"

  db:
    image: descartesresearch/teastore-db
    expose:
      - "3306"
    ports:
      - "3306:3306"

  persistence:
    image: descartesresearch/teastore-persistence
    expose:
      - "8080"
    ports:
      - "8084:8080"
    environment:
      HOST_NAME: "persistence"
      REGISTRY_HOST: "registry"
      DB_HOST: "db"
      DB_PORT: "3306"
      RABBITMQ_HOST: "rabbitmq"
    depends_on:
      - rabbitmq

  auth:
    image: descartesresearch/teastore-auth
    expose:
      - "8080"
    ports:
      - "8085:8080"
    environment:
      HOST_NAME: "auth"
      REGISTRY_HOST: "registry"
      RABBITMQ_HOST: "rabbitmq"
    depends_on:
      - rabbitmq

  image:
    image: descartesresearch/teastore-image
    expose:
      - "8080"
    ports:
      - "8086:8080"
    environment:
      HOST_NAME: "image"
      REGISTRY_HOST: "registry"
      RABBITMQ_HOST: "rabbitmq"
    depends_on:
      - rabbitmq

  recommender:
    image: descartesresearch/teastore-recommender
    expose:
      - "8080"
    ports:
      - "8087:8080"
    environment:
      HOST_NAME: "recommender"
      REGISTRY_HOST: "registry"
      RABBITMQ_HOST: "rabbitmq"
    depends_on:
      - rabbitmq

  webui:
    image: descartesresearch/teastore-webui
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      HOST_NAME: "webui"
      REGISTRY_HOST: "registry"
      RABBITMQ_HOST: "rabbitmq"
    depends_on:
      - rabbitmq

networks:
  default:
    name: teastore-network
