version: '3'
services:
  registry:
    image: descartesresearch/teastore-registry
    expose:
      - "8080"
    ports:
      - "8083:8080"
    networks:
      - teastore-network

  db:
    image: descartesresearch/teastore-db
    expose:
      - "3306"
    ports:
      - "3306:3306"
    networks:
      - teastore-network

  persistence:
    image: descartesresearch/teastore-persistence
    expose:
      - "8080"
    ports:
      - "8084:8080"
    environment:
      HOST_NAME: "persistence"
      REGISTRY_HOST: "registry"
      DB_HOST: "db"
      DB_PORT: "3306"
      LOG_TO_FILE: "true"
      LOG_PARAMETERS: "true"
    volumes:
      - ./logs/persistence:/kieker/logs/
    networks:
      - teastore-network

  auth:
    image: descartesresearch/teastore-auth
    expose:
      - "8080"
    ports:
      - "8085:8080"
    environment:
      HOST_NAME: "auth"
      REGISTRY_HOST: "registry"
      LOG_TO_FILE: "true"
      LOG_PARAMETERS: "true"
    volumes:
      - ./logs/auth:/kieker/logs/
    networks:
      - teastore-network

  image:
    image: descartesresearch/teastore-image
    expose:
      - "8080"
    ports:
      - "8086:8080"
    environment:
      HOST_NAME: "image"
      REGISTRY_HOST: "registry"
      LOG_TO_FILE: "true"
      LOG_PARAMETERS: "true"
    volumes:
      - ./logs/image:/kieker/logs/
    networks:
      - teastore-network

  recommender:
    image: descartesresearch/teastore-recommender
    expose:
      - "8080"
    ports:
      - "8087:8080"
    environment:
      HOST_NAME: "recommender"
      REGISTRY_HOST: "registry"
      LOG_TO_FILE: "true"
      LOG_PARAMETERS: "true"
    volumes:
      - ./logs/recommender:/kieker/logs/
    networks:
      - teastore-network

  webui:
    image: descartesresearch/teastore-webui
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      HOST_NAME: "webui"
      REGISTRY_HOST: "registry"
      LOG_TO_FILE: "true"
      LOG_PARAMETERS: "true"
    volumes:
      - ./logs/webui:/kieker/logs/
    networks:
      - teastore-network

networks:
  teastore-network:
    driver: bridge