version: '3.7'

services:
  rs1_node1:
    image: redislabs/redis:latest
    cap_add:
      - sys_resource
    ports:
      - target: 8443
        published: 8443
        protocol: tcp
        mode: host  # Use host networking mode to avoid routing mesh
      - target: 9443
        published: 9443
        protocol: tcp
        mode: host
      - target: 12000
        published: 12000
        protocol: tcp
        mode: host
    networks:
      - redis_net
    deploy:
      placement:
        constraints:
          - node.hostname==manager-redis

  rs2_node1:
    image: redislabs/redis:latest
    cap_add:
      - sys_resource
    ports:
      - target: 8443
        published: 8443
        protocol: tcp
        mode: host
      - target: 9443
        published: 9443
        protocol: tcp
        mode: host
      - target: 12000
        published: 12000
        protocol: tcp
        mode: host
    networks:
      - redis_net
    deploy:
      placement:
        constraints:
          - node.hostname==load-balancer1

networks:
  redis_net:
    driver: overlay
